webtalk_init -webtalk_dir E:\\Exercise\\FPGA\\FPGA_CNN\\01_mnist_cnn\\vivado\\design.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-08-21 13:26:59" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "92h46chb4qm1krt2m78j07lpjf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.3_4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1597977069391" -context "sdk\\\\bsp/1597977069391"
webtalk_add_data -client sdk -key hwid -value "1597927587543" -context "sdk\\\\bsp/1597977069391"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1597977069391"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1597977069391"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1597977069391"
webtalk_add_data -client sdk -key uid -value "1597977071841" -context "sdk\\\\application/1597977071841"
webtalk_add_data -client sdk -key hwid -value "1597927587543" -context "sdk\\\\application/1597977071841"
webtalk_add_data -client sdk -key bspid -value "1597977069391" -context "sdk\\\\application/1597977071841"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1597977071841"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1597977071841"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1597977071841"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1597977071841"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1597977071841"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1597977071841"
webtalk_add_data -client sdk -key projSize -value "248.8515625" -context "sdk\\\\application/1597977071841"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1597987619086"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1597987619086"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1597987619086"
webtalk_add_data -client sdk -key DebugCount -value "3" -context "sdk\\\\bsp/1597987619086"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1597987619086"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1597987619086"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1597987619086"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1597987619086"
webtalk_transmit -clientid 3242025816 -regid "" -xml E:\\Exercise\\FPGA\\FPGA_CNN\\01_mnist_cnn\\vivado\\design.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\Exercise\\FPGA\\FPGA_CNN\\01_mnist_cnn\\vivado\\design.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\Exercise\\FPGA\\FPGA_CNN\\01_mnist_cnn\\vivado\\design.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
