# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.cache/wt [current_project]
set_property parent.project_path E:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.ipdefs/ip/interface/xilinx.com_user_pldma_rgbin_1.0
  e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.ipdefs/ip/xilinx.com_user_bayer2rgb_1.0
  e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.ipdefs/ip/xilinx.com_user_gpio_mux_1.0
  e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.ipdefs/ip/xilinx.com_user_hdmi_tx_1.0
  e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.ipdefs/ip/xilinx.com_user_pldma_rgbin_1.0
  e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.ipdefs/ip/xilinx.com_user_pldma_rgbout_1.0
} [current_project]
set_property ip_output_repo e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/hdl/pfm_cmos_wrapper.v
add_files E:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/pfm_cmos.bd
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_bayer2rgb_0_0/ip/ram_2x4096x8_2x1024x32/ram_2x4096x8_2x1024x32_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_clk_wiz_0_0/pfm_cmos_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_clk_wiz_0_0/pfm_cmos_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_clk_wiz_0_0/pfm_cmos_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_pldma_rgbin_0_0/hdl/ip/fifo_16384x32_8192x64/fifo_16384x32_8192x64/fifo_16384x32_8192x64.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_pldma_rgbin_0_0/hdl/ip/fifo_16384x32_8192x64/fifo_16384x32_8192x64/fifo_16384x32_8192x64_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_clk_wiz_1_0/pfm_cmos_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_clk_wiz_1_0/pfm_cmos_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_clk_wiz_1_0/pfm_cmos_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_pldma_rgbout_0_2/hdl/ipcore/fifo_8192x64_16384x32/fifo_8192x64_16384x32.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_pldma_rgbout_0_2/hdl/ipcore/fifo_8192x64_16384x32/fifo_8192x64_16384x32_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_rst_ps7_0_200M_4/pfm_cmos_rst_ps7_0_200M_4_board.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_rst_ps7_0_200M_4/pfm_cmos_rst_ps7_0_200M_4.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_rst_ps7_0_200M_4/pfm_cmos_rst_ps7_0_200M_4_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_rst_ps7_0_100M_5/pfm_cmos_rst_ps7_0_100M_5_board.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_rst_ps7_0_100M_5/pfm_cmos_rst_ps7_0_100M_5.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_rst_ps7_0_100M_5/pfm_cmos_rst_ps7_0_100M_5_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_xbar_0/pfm_cmos_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_xbar_1/pfm_cmos_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_processing_system7_0_1/pfm_cmos_processing_system7_0_1.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_auto_pc_0/pfm_cmos_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/ip/pfm_cmos_auto_pc_1/pfm_cmos_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/pfm_cmos_ooc.xdc]
set_property is_locked true [get_files E:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/sources_1/bd/pfm_cmos/pfm_cmos.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/constrs_1/new/pfm_cmos.xdc
set_property used_in_implementation false [get_files E:/Exercise/FPGA/FPGA_CNN/02_cifar10_cnn/vivado/ex01_pfm_cmos/hw/pfm_cmos.srcs/constrs_1/new/pfm_cmos.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top pfm_cmos_wrapper -part xc7z020clg400-1


write_checkpoint -force -noxdef pfm_cmos_wrapper.dcp

catch { report_utilization -file pfm_cmos_wrapper_utilization_synth.rpt -pb pfm_cmos_wrapper_utilization_synth.pb }
