# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.cache/wt [current_project]
set_property parent.project_path E:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/hls [current_project]
set_property ip_output_repo e:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files E:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.srcs/sources_1/bd/design_1/ip/design_1_Conv_0_0/constraints/Conv_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.srcs/sources_1/bd/design_1/ip/design_1_Pool_0_0/constraints/Pool_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files E:/Exercise/FPGA/FPGA_CNN/01_mnist_cnn/vivado/design.srcs/sources_1/bd/design_1/design_1.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7z020clg400-1


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
