#!/bin/bash -f
# Vivado (TM) v2016.4_sdx (64-bit)
#
# Filename    : pfm_cmos.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Aug 28 20:47:58 +0800 2020
# IP Build 1759159 on Thu Jan 26 07:31:30 MST 2017 
#
# usage: pfm_cmos.sh [-help]
# usage: pfm_cmos.sh [-lib_map_path]
# usage: pfm_cmos.sh [-noclean_files]
# usage: pfm_cmos.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'pfm_cmos.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-load "D:/ProgramData/Xilinx/SDx/2016.4/Vivado/lib/win64.o/libxil_vcs.dll:xilinx_register_systf" -full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm blk_mem_gen_v8_3_5 fifo_generator_v13_1_3 lib_pkg_v1_0 lib_srl_fifo_v1_0 axi_lite_ipif_v3_0 axi_master_burst_v2_0 lib_cdc_v1_0_2 proc_sys_reset_v5_0_10 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_11 axi_data_fifo_v2_1_10 axi_crossbar_v2_1_12 processing_system7_bfm_v2_0_5 axi_protocol_converter_v2_1_11)

# Simulation root library directory
sim_lib_dir="vcs"

# Script info
echo -e "pfm_cmos.sh - Script generated by export_simulation (Vivado v2016.4_sdx (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "D:/ProgramData/Xilinx/SDx/2016.4/Vivado/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/ProgramData/Xilinx/SDx/2016.4/Vivado/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/ProgramData/Xilinx/SDx/2016.4/Vivado/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/1188/gpio_mux.v" \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_gpio_mux_0_0/sim/pfm_cmos_gpio_mux_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_3_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/6273/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_bayer2rgb_0_0/ip/ram_2x4096x8_2x1024x32/sim/ram_2x4096x8_2x1024x32.v" \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/4890/sync_em2sp.v" \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/4890/rst_initial.v" \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/4890/mode_det.v" \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/4890/bayer2rgb.v" \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_bayer2rgb_0_0/sim/pfm_cmos_bayer2rgb_0_0.v" \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_clk_wiz_0_0/pfm_cmos_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_clk_wiz_0_0/pfm_cmos_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/564d/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_1_3 $vhdlan_opts \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/564d/hdl/fifo_generator_v13_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/564d/hdl/fifo_generator_v13_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_pldma_rgbin_0_0/hdl/ip/fifo_16384x32_8192x64/sim/fifo_16384x32_8192x64.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/lib_pkg_v1_0/hdl/src/vhdl/lib_pkg.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/lib_srl_fifo_v1_0/hdl/src/vhdl/dynshreg_f.vhd" \
    "$ref_dir/../../../ipstatic/lib_srl_fifo_v1_0/hdl/src/vhdl/cntr_incr_decr_addn_f.vhd" \
    "$ref_dir/../../../ipstatic/lib_srl_fifo_v1_0/hdl/src/vhdl/srl_fifo_rbu_f.vhd" \
    "$ref_dir/../../../ipstatic/lib_srl_fifo_v1_0/hdl/src/vhdl/srl_fifo_f.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0 $vhdlan_opts \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/f8c8/hdl/xilinx/axi_lite_ipif_v3_0/hdl/src/vhdl/pselect_f.vhd" \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/f8c8/hdl/xilinx/axi_lite_ipif_v3_0/hdl/src/vhdl/ipif_pkg.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_master_burst_v2_0 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_wr_demux.vhd" \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_strb_gen.vhd" \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_rdmux.vhd" \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_fifo.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0 $vhdlan_opts \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/f8c8/hdl/xilinx/axi_lite_ipif_v3_0/hdl/src/vhdl/address_decoder.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_master_burst_v2_0 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_wr_status_cntl.vhd" \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_wrdata_cntl.vhd" \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_stbs_set.vhd" \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_skid_buf.vhd" \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_skid2mm_buf.vhd" \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_rd_status_cntl.vhd" \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_rddata_cntl.vhd" \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_pcc.vhd" \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_first_stb_offset.vhd" \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_addr_cntl.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0 $vhdlan_opts \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/f8c8/hdl/xilinx/axi_lite_ipif_v3_0/hdl/src/vhdl/slave_attachment.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_master_burst_v2_0 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_wr_llink.vhd" \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_reset.vhd" \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_rd_wr_cntlr.vhd" \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_rd_llink.vhd" \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst_cmd_status.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0 $vhdlan_opts \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/f8c8/hdl/xilinx/axi_lite_ipif_v3_0/hdl/src/vhdl/axi_lite_ipif.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_master_burst_v2_0 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/axi_master_burst_v2_0/hdl/src/vhdl/axi_master_burst.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/f8c8/hdl/verilog/user_logic_wr.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/f8c8/hdl/vhdl/pldma_rgbin.vhd" \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_pldma_rgbin_0_0/sim/pfm_cmos_pldma_rgbin_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_clk_wiz_1_0/pfm_cmos_clk_wiz_1_0_clk_wiz.v" \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_clk_wiz_1_0/pfm_cmos_clk_wiz_1_0.v" \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_pldma_rgbout_0_2/hdl/ipcore/sim/fifo_8192x64_16384x32.v" \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/a6fa/hdl/verilog/vga720p.v" \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/a6fa/hdl/verilog/user_logic.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/a6fa/hdl/vhdl/pldma_rgbout.vhd" \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_pldma_rgbout_0_2/sim/pfm_cmos_pldma_rgbout_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/52cb/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_10 $vhdlan_opts \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/04b4/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_rst_ps7_0_200M_4/sim/pfm_cmos_rst_ps7_0_200M_4.vhd" \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_rst_ps7_0_100M_5/sim/pfm_cmos_rst_ps7_0_100M_5.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7ee0/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/0b6b/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/39ba/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/896d/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_xbar_0/sim/pfm_cmos_xbar_0.v" \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_xbar_1/sim/pfm_cmos_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/pfm_cmos/ipshared/904f/hdmi_out.srcs/sources_1/imports/src/TMDSEncoder.vhd" \
    "$ref_dir/../../../bd/pfm_cmos/ipshared/904f/hdmi_out.srcs/sources_1/imports/src/SerializerN_1.vhd" \
    "$ref_dir/../../../bd/pfm_cmos/ipshared/904f/hdmi_out.srcs/sources_1/imports/src/DVITransmitter.vhd" \
    "$ref_dir/../../../bd/pfm_cmos/ipshared/904f/hdmi_out.srcs/sources_1/imports/src/hdmi_tx.vhd" \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_hdmi_tx_0_0/sim/pfm_cmos_hdmi_tx_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "$ref_dir/../../../bd/pfm_cmos/ipshared/2e37/xlconcat.v" \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_xlconcat_0_0/sim/pfm_cmos_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_bfm_v2_0_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl/processing_system7_bfm_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_processing_system7_0_1/sim/pfm_cmos_processing_system7_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/df1b/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/100a" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../pfm_cmos.srcs/sources_1/bd/pfm_cmos/ipshared/7dd0/hdl" \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_auto_pc_0/sim/pfm_cmos_auto_pc_0.v" \
    "$ref_dir/../../../bd/pfm_cmos/ip/pfm_cmos_auto_pc_1/sim/pfm_cmos_auto_pc_1.v" \
    "$ref_dir/../../../bd/pfm_cmos/hdl/pfm_cmos.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.pfm_cmos xil_defaultlib.glbl -o pfm_cmos_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./pfm_cmos_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./pfm_cmos.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key pfm_cmos_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc pfm_cmos_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./pfm_cmos.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: pfm_cmos.sh [-help]\n\
Usage: pfm_cmos.sh [-lib_map_path]\n\
Usage: pfm_cmos.sh [-reset_run]\n\
Usage: pfm_cmos.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
